band_1: g
band_2: r
batch:
  max_jobs: 20
catalog:
  basis_1: ra
  basis_2: dec
  data_dir: data_dir
  mag: '{}mag'
  mag_dered: '{}mag0'
  mag_err: '{}err'
  mag_max: 23.5
  nside: 32
  profile: delve_private
isochrone:
  age: 12
  metallicity: 0.0001
  name: Bressan2012
  survey: des
output:
  candidate_list: candidate_list.csv
  log_dir: log_dir
  results_dir: results_dir
  save_dir: plot_dir
survey:
  fracdet: null
  name: des
